services:
  - type: web
    name: safenest-api
    runtime: python
    plan: free
    envVars:
      - key: MYSQL_PUBLIC_URL
        value: mysql://root:tyDBDKDwgXXuUFhOoeWPFCMELNYvwdYI@turntable.proxy.rlwy.net:18759/railway
      - key: SAFENEST_SECRET
        value: your_strong_secret_here
      - key: PYTHON_VERSION
        value: 3.11.0

    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn apiSQL:app --host 0.0.0.0 --port $PORT"